// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXEbaQB3NF9giWNUZv767A9kL3rMKDhzM',
    appId: '1:196578923544:web:30bdf11889808bad93df6d',
    messagingSenderId: '196578923544',
    projectId: 'my-todo-list-app-with-ca',
    authDomain: 'my-todo-list-app-with-ca.firebaseapp.com',
    storageBucket: 'my-todo-list-app-with-ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhBh-DG17VEJt4S7oxZ9HY5SKkydEpBVg',
    appId: '1:196578923544:android:2267c355803b5f2893df6d',
    messagingSenderId: '196578923544',
    projectId: 'my-todo-list-app-with-ca',
    storageBucket: 'my-todo-list-app-with-ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxbtjaqX8J11T2zMoCtgsG3LswK1OH8KU',
    appId: '1:196578923544:ios:ceefdb47b78431cc93df6d',
    messagingSenderId: '196578923544',
    projectId: 'my-todo-list-app-with-ca',
    storageBucket: 'my-todo-list-app-with-ca.appspot.com',
    iosBundleId: 'dev.rochajohnathan.todoListCleanArchitecture',
  );
}
